openapi: '3.0.2'
info:
  title: 'Metadata Service'
  description: 'Used to communicate with Neo4j or Apache Atlas for get metadata.'
  version: '1.1.12'

components:
  schemas:
    ErrorResponse:
      type: object
      properties:
        message:
          type: string
          description: 'A simple description of what went wrong'
          example: 'An Exception encountered while processing your request'